baseURL = 'https://mertyesiladali.github.io/'
languageCode = 'tr-tr'
title = 'Dr. Mert Yeşiladalı - Jinekolog'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'
